apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169802128
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169802128
    app.kubernetes.io/part-of: test-app-169802128
  name: java-quarkus-169802128
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169802128
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169802128
    spec:
      containers:
      - image: quay.io/hacdev/ons8wzj6-tenant/test-app-169802128/java-quarkus-169802128@sha256:73e65ad6876544893c7bef3579da7617373022699b0971a57150e98cfa3244f7
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
